### ISSUE TITLE
The `job/oops` malfunctions

### ISSUE THREAD

**Issue by pkosiec** [pkosiec/botkube-plugins#1]
## Description

This issue refers to the problems connected with 
```bash
job/oops
```
 in namespace 
```bash
default
```

<details>
  <summary><b>Logs</b></summary>

```bash
Hello from failing job!

```

</details>

### Cluster details

```yaml
clientVersion:
  buildDate: "2022-12-08T19:58:30Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: darwin/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-09-28T16:29:54Z"
  compiler: gc
  gitCommit: 53c268d8eb90ceea5e1c7865f89db5c7fb8763bc
  gitTreeState: clean
  gitVersion: v1.25.2+k3s1
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/arm64


```
